services:
  app:
    build: .
    environment:
      - PGHOST=host.docker.internal  
      - PGPORT=5432
      - PGDATABASE=rag_fin
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./data:/app/data
    extra_hosts:
      - "host.docker.internal:host-gateway" 